<?php

namespace App\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use App\MainBundle\Entity\Publisher;

/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends EntityRepository
{
    public function create(){
        return new Publisher();
    }

    public function save(Publisher $publisher){
        $this->getEntityManager()->persist($publisher);
        $this->getEntityManager()->flush();
    }
}
